name: ESP32 Arduino Libs CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:

  build-libs:
    name: Build Arduino Libs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install git wget curl libssl-dev libncurses-dev flex bison gperf python python-pip python-setuptools python-serial python-click python-cryptography python-future python-pyparsing python-pyelftools cmake ninja-build ccache
    - name: Install Python Wheel
      run: pip install wheel
    - name: Build Arduino Libs
      run: bash ./init_build.sh
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: dist
